name: CICD
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: k8s-web
        uses: actions/checkout@v4


      - name: k8swebdeploy
        run: cd k8s-web-h

      - name: k8swebdeploy
        run: cp k8s-web-h/package.json \k8s-web-h/package-lock.json \.

      - name: k8swebdeploy
        run: cp k8s-web-h/dockerfile \.

      - name: build
        run: docker build -t bharath6379/k8s-web:1.1.26 .

      - name: dockerlogin
        run: docker login -u ${{secrets.Docker_username}}} --password-stdin <<< "${{secrets.Docker_password}}"

      - name: dockerpush
        run: docker push bharath6379/k8s-web:1.1.26
